language: php

php: 
  - 5.3
  - 5.4
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script: 
  - "psql -c 'create database doctrine_tests;' -U postgres"
  - "psql -c 'create database doctrine_tests_tmp;' -U postgres"
  - "mysql -e 'create database doctrine_tests_tmp;create database doctrine_tests;'"
  - git submodule update --init

script: phpunit --configuration $DB.phpunit.xml
